apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 302go
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KoukeNeko/homelab-gitops.git
    targetRevision: main
    path: apps/302.go
  destination:
    server: https://kubernetes.default.svc
    namespace: 302go
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
